#!/usr/bin/env bash
# NIRNAY launcher.
#   ./run.sh            Docker Compose if available, otherwise local dev mode
#   ./run.sh docker     full stack (frontend, backend, worker, PostgreSQL/PostGIS, Redis)
#   ./run.sh dev        no Docker: Python venv + SQLite + in-process bus + Vite dev server
#   ./run.sh test       backend pytest + frontend vitest
#   ./run.sh stop       stop the Docker stack
set -euo pipefail
cd "$(dirname "$0")"
ROOT="$PWD"
MODE="${1:-auto}"

log() { printf '\033[1;36m[nirnay]\033[0m %s\n' "$*"; }
die() { printf '\033[1;31m[nirnay]\033[0m %s\n' "$*" >&2; exit 1; }

PY="${PYTHON:-python3}"

rand() { "$PY" -c "import secrets;print(secrets.token_urlsafe(${1:-48}))"; }

ensure_env() {
  # Create .env from the template with freshly generated secrets (never committed).
  if [[ ! -f .env ]]; then
    log "creating .env with generated secrets"
    cp .env.example .env
    {
      echo ""
      echo "# --- generated by run.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ) ---"
      echo "JWT_SECRET=$(rand 48)"
      echo "PSEUDONYM_SECRET=$(rand 32)"
      echo "POSTGRES_PASSWORD=$(rand 24)"
    } >> .env
    if "$PY" -c "import cryptography" 2>/dev/null; then
      echo "ENCRYPTION_KEY=$("$PY" -c 'from cryptography.fernet import Fernet;print(Fernet.generate_key().decode())')" >> .env
    fi
  fi
}

have_docker() { command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; }

run_docker() {
  have_docker || die "Docker with the compose plugin is required (or use ./run.sh dev)"
  ensure_env
  grep -q '^ENCRYPTION_KEY=' .env || die "ENCRYPTION_KEY missing in .env (install python3-cryptography or set it manually)"
  log "building and starting the stack (first build downloads the models)…"
  docker compose up --build -d
  log "waiting for the API to become ready…"
  for _ in $(seq 1 90); do
    if docker compose exec -T backend curl -fsS http://127.0.0.1:8000/ready >/dev/null 2>&1; then
      log "ready → http://localhost:3000  (demo logins: admin / operator / analyst / viewer, password from DEMO_PASSWORD)"
      return 0
    fi
    sleep 2
  done
  docker compose ps
  die "backend did not become ready; see: docker compose logs backend worker"
}

setup_python() {
  command -v "$PY" >/dev/null || die "python3 (3.11+) is required"
  if [[ ! -x backend/.venv/bin/python && ! -x .venv/bin/python ]]; then
    log "creating Python virtualenv (.venv)"
    "$PY" -m venv .venv
  fi
  VENV_PY="$ROOT/.venv/bin/python"
  [[ -x "$VENV_PY" ]] || VENV_PY="$ROOT/backend/.venv/bin/python"
  if ! "$VENV_PY" -c "import fastapi, onnxruntime, cv2" 2>/dev/null; then
    log "installing backend dependencies"
    "$VENV_PY" -m pip install -q --upgrade pip
    "$VENV_PY" -m pip install -q -r backend/requirements-dev.txt
  fi
  if ! "$VENV_PY" scripts/download_models.py --verify >/dev/null 2>&1; then
    log "downloading models (one-time)"
    "$VENV_PY" scripts/download_models.py || log "model download failed — the pipeline will use its documented fallbacks"
  fi
}

setup_node() {
  command -v npm >/dev/null || die "Node.js 20+ and npm are required for the frontend"
  if [[ ! -d frontend/node_modules ]]; then
    log "installing frontend dependencies"
    (cd frontend && npm ci --no-audit --no-fund 2>/dev/null || npm install --no-audit --no-fund)
  fi
}

run_dev() {
  ensure_env
  setup_python
  setup_node
  mkdir -p data
  log "starting backend on http://127.0.0.1:8000 (SQLite + in-process bus + embedded workers)"
  (cd backend && exec "$VENV_PY" -m uvicorn app.main:app --host 127.0.0.1 --port 8000) &
  BACK=$!
  trap 'log "stopping"; kill $BACK $FRONT 2>/dev/null || true; wait 2>/dev/null' EXIT INT TERM
  for _ in $(seq 1 60); do
    curl -fsS http://127.0.0.1:8000/health >/dev/null 2>&1 && break
    kill -0 $BACK 2>/dev/null || die "backend exited during startup"
    sleep 1
  done
  log "starting frontend on http://localhost:3000"
  (cd frontend && exec npm run dev -- --host 127.0.0.1) &
  FRONT=$!
  log "open http://localhost:3000 — demo logins admin / operator / analyst / viewer (password: DEMO_PASSWORD, default nirnay-demo)"
  wait
}

run_tests() {
  setup_python
  setup_node
  log "backend tests"
  (cd backend && "$VENV_PY" -m pytest -q)
  log "frontend typecheck + tests"
  (cd frontend && npm run typecheck && npm test)
}

case "$MODE" in
  auto) if have_docker; then run_docker; else log "Docker not found — using local dev mode"; run_dev; fi ;;
  docker) run_docker ;;
  dev) run_dev ;;
  test) run_tests ;;
  stop) docker compose down ;;
  *) die "usage: ./run.sh [docker|dev|test|stop]" ;;
esac
