#!/usr/bin/env bash
# NIRNAY one-shot setup for Oracle Cloud Always Free (Ubuntu 22.04/24.04, ARM or AMD).
# Run as root on a fresh VM:  curl -fsSL .../oracle/setup.sh | bash   (or bash oracle/setup.sh)
# It installs Docker, clones the repo, generates secrets, and starts the full stack:
# frontend (3000) + backend API (8000) + worker + PostgreSQL/PostGIS + Redis.
set -euo pipefail

APP_DIR="${APP_DIR:-/opt/nirnay}"
REPO="${REPO:-https://github.com/Ayushh890/sih-26127}"
ADMIN_USER="${ADMIN_USER:-admin}"

log() { printf '\033[1;36m[nirnay]\033[0m %s\n' "$*"; }
need_root() { [ "$(id -u)" = 0 ] || { echo "[nirnay] run as root (sudo bash $0)" >&2; exit 1; }; }

need_root

if ! command -v docker >/dev/null 2>&1; then
  log "installing Docker"
  curl -fsSL https://get.docker.com | sh
  systemctl enable --now docker
fi
docker compose version >/dev/null 2>&1 || { echo "[nirnay] docker compose plugin missing" >&2; exit 1; }

if [ ! -d "$APP_DIR/.git" ]; then
  log "cloning $REPO into $APP_DIR"
  git --version >/dev/null 2>&1 || { apt-get update -qq && apt-get install -y -qq git; }
  git clone "$REPO" "$APP_DIR"
fi
cd "$APP_DIR"
git pull --ff-only 2>/dev/null || true

if [ ! -f .env ]; then
  log "generating .env with secrets"
  cp .env.example .env
  rand() { python3 -c "import secrets;print(secrets.token_urlsafe($1))"; }
  {
    echo ""
    echo "# --- generated by oracle/setup.sh ---"
    echo "JWT_SECRET=$(rand 48)"
    echo "PSEUDONYM_SECRET=$(rand 32)"
    echo "POSTGRES_PASSWORD=$(rand 24)"
    echo "ENCRYPTION_KEY=$(python3 -c 'from cryptography.fernet import Fernet;print(Fernet.generate_key().decode())' 2>/dev/null || rand 44)"
  } >> .env
  # Production defaults: no demo accounts; bootstrap a real admin instead.
  sed -i 's/^APP_ENV=.*/APP_ENV=production/' .env
  sed -i 's/^DEMO_USERS=.*/DEMO_USERS=false/' .env
  sed -i 's/^SEED_DEMO=.*/SEED_DEMO=false/' .env
  sed -i 's/^DEMO_AUTOSTART=.*/DEMO_AUTOSTART=false/' .env
  ADMIN_PASS="$(rand 24)"
  sed -i "s/^# ADMIN_USERNAME=/ADMIN_USERNAME=/" .env
  printf 'ADMIN_USERNAME=%s\n' "$ADMIN_USER" >> .env
  printf 'ADMIN_PASSWORD=%s\n' "$ADMIN_PASS" >> .env
  chmod 600 .env
  printf 'NIRNAY admin login\nURL: http://<this-VM-public-IP>:3000\nusername: %s\npassword: %s\n' "$ADMIN_USER" "$ADMIN_PASS" > /root/nirnay-credentials.txt
  chmod 600 /root/nirnay-credentials.txt
  log "admin credentials saved to /root/nirnay-credentials.txt"
fi

log "building and starting the stack (first build takes a few minutes)"
docker compose up --build -d
log "waiting for the API (up to 5 min)"
for _ in $(seq 1 150); do
  if docker compose exec -T backend curl -fsS http://127.0.0.1:8000/ready >/dev/null 2>&1; then
    PUBLIC_IP="$(curl -fsS --max-time 5 https://icanhazip.com 2>/dev/null || echo '<VM-public-IP>')"
    log "READY -> http://${PUBLIC_IP}:3000  (login details in /root/nirnay-credentials.txt)"
    exit 0
  fi
  sleep 2
done
docker compose ps
echo "[nirnay] backend did not become ready; see: docker compose logs backend worker" >&2
exit 1
