"""Data scope: synthetic demo data and live data are never silently mixed.

Every analytics/search endpoint takes ``scope`` = ``live`` | ``demo`` | ``all``. When not
given, ``live`` is used if any non-demo camera exists, otherwise ``demo``. Responses
state the scope they were computed for so the UI can label synthetic data.
"""
from __future__ import annotations

from typing import Any

from sqlalchemy import exists, select
from sqlalchemy.orm import Session

from app.db.models import Camera

SCOPES = ("live", "demo", "all")


def resolve_scope(db: Session, scope: str | None) -> str:
    if scope in SCOPES:
        return scope  # type: ignore[return-value]
    has_live = db.scalar(select(exists().where(Camera.is_demo.is_(False))))
    return "live" if has_live else "demo"


def demo_filter(column: Any, scope: str) -> Any:
    """SQL condition on an ``is_demo`` column for the scope (``None`` = no filter)."""
    if scope == "live":
        return column.is_(False)
    if scope == "demo":
        return column.is_(True)
    return None


def apply_scope(q: Any, column: Any, scope: str) -> Any:
    cond = demo_filter(column, scope)
    return q.where(cond) if cond is not None else q


def scope_info(scope: str) -> dict[str, Any]:
    return {"scope": scope, "synthetic": scope in ("demo", "all"),
            "notice": {"demo": "Synthetic demo data generated by the demo traffic scenario.",
                       "all": "Includes synthetic demo data alongside live data.", "live": None}[scope]}


def scope_camera_ids(db: Session, scope: str) -> list[str]:
    q = apply_scope(select(Camera.id), Camera.is_demo, scope)
    return list(db.scalars(q))
