"""initial schema

All tables and indexes of the ORM models. On PostgreSQL with PostGIS available it also
adds generated ``geom`` columns (from latitude/longitude or the stored GeoJSON) with GiST
indexes, so spatial SQL works without the ORM managing geometry objects.

Revision ID: 0001
Revises: 
Create Date: 2026-09-30 12:05:43.634559
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.db.base


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=14), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('camera_id', sa.String(length=32), nullable=True),
    sa.Column('global_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('observation_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('details', app.db.base.JSONType(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence_id', sa.String(length=36), nullable=True),
    sa.Column('dedup_key', sa.String(length=128), nullable=True),
    sa.Column('occurrences', sa.Integer(), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=64), nullable=True),
    sa.Column('acknowledged_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=64), nullable=True),
    sa.Column('resolved_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts')),
    sa.UniqueConstraint('code', name=op.f('uq_alerts_code'))
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_dedup_key'), ['dedup_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_global_vehicle_id'), ['global_vehicle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_type'), ['type'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('details', app.db.base.JSONType(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_ts'), ['ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_username'), ['username'], unique=False)

    op.create_table('cameras',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('source_uri', sa.Text(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password_encrypted', sa.Text(), nullable=True),
    sa.Column('resolution', sa.String(length=16), nullable=True),
    sa.Column('lane_count', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('road_name', sa.String(length=128), nullable=False),
    sa.Column('zone', sa.String(length=64), nullable=False),
    sa.Column('camera_type', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('status_message', sa.Text(), nullable=False),
    sa.Column('last_seen_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('processing', app.db.base.JSONType(), nullable=False),
    sa.Column('calibration', app.db.base.JSONType(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cameras'))
    )
    op.create_table('dead_letters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('camera_id', sa.String(length=32), nullable=True),
    sa.Column('payload', app.db.base.JSONType(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('resolution', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dead_letters'))
    )
    with op.batch_alter_table('dead_letters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dead_letters_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_dead_letters_resolved'), ['resolved'], unique=False)
        batch_op.create_index(batch_op.f('ix_dead_letters_ts'), ['ts'], unique=False)

    op.create_table('evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('observation_id', sa.Integer(), nullable=True),
    sa.Column('camera_id', sa.String(length=32), nullable=False),
    sa.Column('ts', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('files', app.db.base.JSONType(), nullable=False),
    sa.Column('bbox', app.db.base.JSONType(), nullable=True),
    sa.Column('plate_bbox', app.db.base.JSONType(), nullable=True),
    sa.Column('ocr_text', sa.String(length=32), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('manifest_sha256', sa.String(length=64), nullable=False),
    sa.Column('encrypted', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence'))
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_observation_id'), ['observation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_ts'), ['ts'], unique=False)

    op.create_table('global_vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('plate_text', sa.String(length=16), nullable=True),
    sa.Column('plate_confidence', sa.Float(), nullable=True),
    sa.Column('plate_hash', sa.String(length=64), nullable=True),
    sa.Column('vehicle_class', sa.String(length=16), nullable=True),
    sa.Column('vehicle_color', sa.String(length=16), nullable=True),
    sa.Column('first_seen_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('first_camera_id', sa.String(length=32), nullable=True),
    sa.Column('last_camera_id', sa.String(length=32), nullable=True),
    sa.Column('last_observation_id', sa.Integer(), nullable=True),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.Column('camera_count', sa.Integer(), nullable=False),
    sa.Column('total_distance_m', sa.Float(), nullable=False),
    sa.Column('predicted_camera_id', sa.String(length=32), nullable=True),
    sa.Column('predicted_from_observation_id', sa.Integer(), nullable=True),
    sa.Column('predicted_window_start', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('predicted_window_end', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('predicted_probability', sa.Float(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_global_vehicles'))
    )
    with op.batch_alter_table('global_vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_global_vehicles_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_global_vehicles_first_seen_at'), ['first_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_global_vehicles_last_camera_id'), ['last_camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_global_vehicles_last_seen_at'), ['last_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_global_vehicles_plate_hash'), ['plate_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_global_vehicles_plate_text'), ['plate_text'], unique=False)

    op.create_table('roads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('geojson', app.db.base.JSONType(), nullable=False),
    sa.Column('speed_limit_kmh', sa.Float(), nullable=False),
    sa.Column('lanes', sa.Integer(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roads'))
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('permissions', app.db.base.JSONType(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('system_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('camera_id', sa.String(length=32), nullable=True),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', app.db.base.JSONType(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_events'))
    )
    with op.batch_alter_table('system_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_events_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_events_ts'), ['ts'], unique=False)

    op.create_table('system_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', app.db.base.JSONType(), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_system_settings'))
    )
    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate', sa.String(length=16), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('match_mode', sa.String(length=8), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_match_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('match_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watchlist'))
    )
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlist_plate'), ['plate'], unique=False)

    op.create_table('worker_heartbeats',
    sa.Column('worker_id', sa.String(length=64), nullable=False),
    sa.Column('ts', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('info', app.db.base.JSONType(), nullable=False),
    sa.PrimaryKeyConstraint('worker_id', name=op.f('pk_worker_heartbeats'))
    )
    op.create_table('camera_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_camera_id', sa.String(length=32), nullable=False),
    sa.Column('to_camera_id', sa.String(length=32), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('min_travel_s', sa.Float(), nullable=False),
    sa.Column('typical_travel_s', sa.Float(), nullable=False),
    sa.Column('road_name', sa.String(length=128), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('road_id', sa.Integer(), nullable=True),
    sa.Column('path_geojson', app.db.base.JSONType(), nullable=True),
    sa.ForeignKeyConstraint(['from_camera_id'], ['cameras.id'], name=op.f('fk_camera_edges_from_camera_id_cameras'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['road_id'], ['roads.id'], name=op.f('fk_camera_edges_road_id_roads'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_camera_id'], ['cameras.id'], name=op.f('fk_camera_edges_to_camera_id_cameras'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_camera_edges')),
    sa.UniqueConstraint('from_camera_id', 'to_camera_id', name='uq_edge_pair')
    )
    with op.batch_alter_table('camera_edges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_camera_edges_from_camera_id'), ['from_camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_camera_edges_to_camera_id'), ['to_camera_id'], unique=False)

    op.create_table('camera_health',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.String(length=32), nullable=False),
    sa.Column('ts', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('input_fps', sa.Float(), nullable=False),
    sa.Column('processing_fps', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('inference_ms', sa.Float(), nullable=False),
    sa.Column('queue_depth', sa.Integer(), nullable=False),
    sa.Column('frames_processed', sa.Integer(), nullable=False),
    sa.Column('frames_dropped', sa.Integer(), nullable=False),
    sa.Column('vehicles_detected', sa.Integer(), nullable=False),
    sa.Column('plates_read', sa.Integer(), nullable=False),
    sa.Column('avg_ocr_confidence', sa.Float(), nullable=True),
    sa.Column('blur_score', sa.Float(), nullable=True),
    sa.Column('brightness', sa.Float(), nullable=True),
    sa.Column('reconnects', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_camera_health_camera_id_cameras'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_camera_health'))
    )
    with op.batch_alter_table('camera_health', schema=None) as batch_op:
        batch_op.create_index('ix_camera_health_cam_ts', ['camera_id', 'ts'], unique=False)

    op.create_table('traffic_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.String(length=32), nullable=False),
    sa.Column('bucket_start', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('bucket_seconds', sa.Integer(), nullable=False),
    sa.Column('frames', sa.Integer(), nullable=False),
    sa.Column('new_tracks', sa.Integer(), nullable=False),
    sa.Column('avg_vehicles_in_frame', sa.Float(), nullable=False),
    sa.Column('max_vehicles_in_frame', sa.Integer(), nullable=False),
    sa.Column('occupancy', sa.Float(), nullable=False),
    sa.Column('avg_stationary', sa.Float(), nullable=False),
    sa.Column('avg_speed_kmh', sa.Float(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_traffic_metrics_camera_id_cameras'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_traffic_metrics')),
    sa.UniqueConstraint('camera_id', 'bucket_start', name='uq_metric_bucket')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('vehicle_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.String(length=32), nullable=False),
    sa.Column('local_track_id', sa.Integer(), nullable=False),
    sa.Column('started_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('ended_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('vehicle_class', sa.String(length=16), nullable=False),
    sa.Column('class_confidence', sa.Float(), nullable=False),
    sa.Column('frames', sa.Integer(), nullable=False),
    sa.Column('path', app.db.base.JSONType(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_vehicle_tracks_camera_id_cameras'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicle_tracks'))
    )
    with op.batch_alter_table('vehicle_tracks', schema=None) as batch_op:
        batch_op.create_index('ix_vehicle_tracks_cam_started', ['camera_id', 'started_at'], unique=False)

    op.create_table('vehicle_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('camera_id', sa.String(length=32), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('local_track_id', sa.Integer(), nullable=False),
    sa.Column('observed_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('first_seen_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('plate_text', sa.String(length=16), nullable=True),
    sa.Column('plate_raw', sa.String(length=32), nullable=True),
    sa.Column('plate_confidence', sa.Float(), nullable=True),
    sa.Column('plate_valid', sa.Boolean(), nullable=False),
    sa.Column('plate_hash', sa.String(length=64), nullable=True),
    sa.Column('plate_votes', sa.Integer(), nullable=False),
    sa.Column('vehicle_class', sa.String(length=16), nullable=False),
    sa.Column('class_confidence', sa.Float(), nullable=False),
    sa.Column('vehicle_color', sa.String(length=16), nullable=True),
    sa.Column('color_rgb', app.db.base.JSONType(), nullable=True),
    sa.Column('bbox', app.db.base.JSONType(), nullable=True),
    sa.Column('speed_kmh', sa.Float(), nullable=True),
    sa.Column('direction', sa.String(length=8), nullable=True),
    sa.Column('heading_deg', sa.Float(), nullable=True),
    sa.Column('motion', sa.String(length=16), nullable=True),
    sa.Column('lane', sa.Integer(), nullable=True),
    sa.Column('global_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('previous_observation_id', sa.Integer(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('match_confidence_level', sa.String(length=8), nullable=True),
    sa.Column('match_reasons', app.db.base.JSONType(), nullable=True),
    sa.Column('match_components', app.db.base.JSONType(), nullable=True),
    sa.Column('evidence_id', sa.String(length=36), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_vehicle_observations_camera_id_cameras'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['global_vehicle_id'], ['global_vehicles.id'], name=op.f('fk_vehicle_observations_global_vehicle_id_global_vehicles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['track_id'], ['vehicle_tracks.id'], name=op.f('fk_vehicle_observations_track_id_vehicle_tracks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicle_observations')),
    sa.UniqueConstraint('event_id', name=op.f('uq_vehicle_observations_event_id'))
    )
    with op.batch_alter_table('vehicle_observations', schema=None) as batch_op:
        batch_op.create_index('ix_obs_cam_time', ['camera_id', 'observed_at'], unique=False)
        batch_op.create_index('ix_obs_gv_time', ['global_vehicle_id', 'observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_observations_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_observations_global_vehicle_id'), ['global_vehicle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_observations_observed_at'), ['observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_observations_plate_hash'), ['plate_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_observations_plate_text'), ['plate_text'], unique=False)

    op.create_table('plate_reads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observation_id', sa.Integer(), nullable=True),
    sa.Column('camera_id', sa.String(length=32), nullable=False),
    sa.Column('local_track_id', sa.Integer(), nullable=False),
    sa.Column('ts', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('raw_text', sa.String(length=32), nullable=False),
    sa.Column('normalized_text', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('char_confidences', app.db.base.JSONType(), nullable=True),
    sa.Column('is_valid_format', sa.Boolean(), nullable=False),
    sa.Column('corrections', app.db.base.JSONType(), nullable=True),
    sa.Column('plate_bbox', app.db.base.JSONType(), nullable=True),
    sa.ForeignKeyConstraint(['observation_id'], ['vehicle_observations.id'], name=op.f('fk_plate_reads_observation_id_vehicle_observations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plate_reads'))
    )
    with op.batch_alter_table('plate_reads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plate_reads_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plate_reads_normalized_text'), ['normalized_text'], unique=False)
        batch_op.create_index(batch_op.f('ix_plate_reads_observation_id'), ['observation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plate_reads_ts'), ['ts'], unique=False)

    op.create_table('trajectory_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_vehicle_id', sa.Integer(), nullable=False),
    sa.Column('observation_id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.String(length=32), nullable=False),
    sa.Column('ts', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('journey_index', sa.Integer(), nullable=False),
    sa.Column('from_camera_id', sa.String(length=32), nullable=True),
    sa.Column('segment_travel_s', sa.Float(), nullable=True),
    sa.Column('segment_distance_m', sa.Float(), nullable=True),
    sa.Column('segment_speed_kmh', sa.Float(), nullable=True),
    sa.Column('link_score', sa.Float(), nullable=True),
    sa.Column('confidence_level', sa.String(length=8), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('prediction_status', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['global_vehicle_id'], ['global_vehicles.id'], name=op.f('fk_trajectory_points_global_vehicle_id_global_vehicles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['observation_id'], ['vehicle_observations.id'], name=op.f('fk_trajectory_points_observation_id_vehicle_observations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trajectory_points')),
    sa.UniqueConstraint('observation_id', name=op.f('uq_trajectory_points_observation_id'))
    )
    with op.batch_alter_table('trajectory_points', schema=None) as batch_op:
        batch_op.create_index('ix_traj_pair_time', ['from_camera_id', 'camera_id', 'ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_trajectory_points_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trajectory_points_global_vehicle_id'), ['global_vehicle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trajectory_points_ts'), ['ts'], unique=False)

    op.create_table('vehicle_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observation_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('vector', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['vehicle_observations.id'], name=op.f('fk_vehicle_embeddings_observation_id_vehicle_observations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicle_embeddings')),
    sa.UniqueConstraint('observation_id', name=op.f('uq_vehicle_embeddings_observation_id'))
    )
    # ### end Alembic commands ###
    _postgis_up()


def downgrade() -> None:
    _postgis_down()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle_embeddings')
    with op.batch_alter_table('trajectory_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trajectory_points_ts'))
        batch_op.drop_index(batch_op.f('ix_trajectory_points_global_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_trajectory_points_camera_id'))
        batch_op.drop_index('ix_traj_pair_time')

    op.drop_table('trajectory_points')
    with op.batch_alter_table('plate_reads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plate_reads_ts'))
        batch_op.drop_index(batch_op.f('ix_plate_reads_observation_id'))
        batch_op.drop_index(batch_op.f('ix_plate_reads_normalized_text'))
        batch_op.drop_index(batch_op.f('ix_plate_reads_camera_id'))

    op.drop_table('plate_reads')
    with op.batch_alter_table('vehicle_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_observations_plate_text'))
        batch_op.drop_index(batch_op.f('ix_vehicle_observations_plate_hash'))
        batch_op.drop_index(batch_op.f('ix_vehicle_observations_observed_at'))
        batch_op.drop_index(batch_op.f('ix_vehicle_observations_global_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_vehicle_observations_camera_id'))
        batch_op.drop_index('ix_obs_gv_time')
        batch_op.drop_index('ix_obs_cam_time')

    op.drop_table('vehicle_observations')
    with op.batch_alter_table('vehicle_tracks', schema=None) as batch_op:
        batch_op.drop_index('ix_vehicle_tracks_cam_started')

    op.drop_table('vehicle_tracks')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('traffic_metrics')
    with op.batch_alter_table('camera_health', schema=None) as batch_op:
        batch_op.drop_index('ix_camera_health_cam_ts')

    op.drop_table('camera_health')
    with op.batch_alter_table('camera_edges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_camera_edges_to_camera_id'))
        batch_op.drop_index(batch_op.f('ix_camera_edges_from_camera_id'))

    op.drop_table('camera_edges')
    op.drop_table('worker_heartbeats')
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlist_plate'))

    op.drop_table('watchlist')
    op.drop_table('system_settings')
    with op.batch_alter_table('system_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_events_ts'))
        batch_op.drop_index(batch_op.f('ix_system_events_camera_id'))

    op.drop_table('system_events')
    op.drop_table('roles')
    op.drop_table('roads')
    with op.batch_alter_table('global_vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_global_vehicles_plate_text'))
        batch_op.drop_index(batch_op.f('ix_global_vehicles_plate_hash'))
        batch_op.drop_index(batch_op.f('ix_global_vehicles_last_seen_at'))
        batch_op.drop_index(batch_op.f('ix_global_vehicles_last_camera_id'))
        batch_op.drop_index(batch_op.f('ix_global_vehicles_first_seen_at'))
        batch_op.drop_index(batch_op.f('ix_global_vehicles_code'))

    op.drop_table('global_vehicles')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_ts'))
        batch_op.drop_index(batch_op.f('ix_evidence_observation_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_camera_id'))

    op.drop_table('evidence')
    with op.batch_alter_table('dead_letters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dead_letters_ts'))
        batch_op.drop_index(batch_op.f('ix_dead_letters_resolved'))
        batch_op.drop_index(batch_op.f('ix_dead_letters_event_type'))

    op.drop_table('dead_letters')
    op.drop_table('cameras')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_username'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_ts'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_type'))
        batch_op.drop_index(batch_op.f('ix_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_alerts_global_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_dedup_key'))
        batch_op.drop_index(batch_op.f('ix_alerts_created_at'))
        batch_op.drop_index(batch_op.f('ix_alerts_camera_id'))

    op.drop_table('alerts')
    # ### end Alembic commands ###


# --------------------------------------------------------------------------- PostGIS
POINT_TABLES = ("cameras", "trajectory_points")
GEOJSON_COLUMNS = (("roads", "geojson"), ("camera_edges", "path_geojson"))


def _has_postgis() -> bool:
    from alembic import context

    if context.is_offline_mode():  # `alembic upgrade --sql`: emit the PostGIS DDL for review
        return context.get_context().dialect.name == "postgresql"
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return False
    return bind.execute(sa.text("SELECT 1 FROM pg_available_extensions WHERE name = 'postgis'")).scalar() is not None


def _postgis_up() -> None:
    if not _has_postgis():
        return
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    for table in POINT_TABLES:
        op.execute(f"ALTER TABLE {table} ADD COLUMN geom geometry(Point, 4326) "
                   f"GENERATED ALWAYS AS (ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)) STORED")
        op.execute(f"CREATE INDEX ix_{table}_geom ON {table} USING GIST (geom)")
    for table, column in GEOJSON_COLUMNS:
        op.execute(f"ALTER TABLE {table} ADD COLUMN geom geometry(Geometry, 4326) "
                   f"GENERATED ALWAYS AS (ST_SetSRID(ST_GeomFromGeoJSON(({column})::text), 4326)) STORED")
        op.execute(f"CREATE INDEX ix_{table}_geom ON {table} USING GIST (geom)")


def _postgis_down() -> None:
    from alembic import context

    if (context.get_context().dialect.name if context.is_offline_mode() else op.get_bind().dialect.name) != "postgresql":
        return
    for table in POINT_TABLES + tuple(t for t, _ in GEOJSON_COLUMNS):
        op.execute(f"DROP INDEX IF EXISTS ix_{table}_geom")
        op.execute(f"ALTER TABLE {table} DROP COLUMN IF EXISTS geom")
