import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { act, cleanup, render, screen, waitFor, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { MemoryRouter, Route, Routes } from "react-router-dom";
import type { ReactNode } from "react";

// Capture live-event subscriptions so tests can push WebSocket events.
const live = vi.hoisted(() => ({ handlers: new Map<string, Set<(ev: { type: string; data: unknown }) => void>>() }));
vi.mock("../lib/ws", async () => {
  const { useEffect, useRef } = await import("react");
  return {
    useConnState: () => "open",
    useLiveEvent: (types: string | string[], handler: (ev: { type: string; data: unknown }) => void) => {
      const ref = useRef(handler);
      ref.current = handler;
      const key = Array.isArray(types) ? types.join(",") : types;
      useEffect(() => {
        const fns = key.split(",").map((t) => {
          const fn = (ev: { type: string; data: unknown }) => ref.current(ev);
          if (!live.handlers.has(t)) live.handlers.set(t, new Set());
          live.handlers.get(t)!.add(fn);
          return [t, fn] as const;
        });
        return () => fns.forEach(([t, fn]) => live.handlers.get(t)?.delete(fn));
      }, [key]);
    },
  };
});

import { AuthProvider } from "../lib/auth";
import { ScopeProvider } from "../lib/scope";
import Alerts from "../pages/Alerts";
import AlertDetail from "../pages/AlertDetail";
import Analytics from "../pages/Analytics";
import Watchlist from "../pages/Watchlist";

const ALL_PERMS = [
  "alerts:act", "alerts:read", "analytics:od_individual", "analytics:read", "cameras:read", "evidence:read", "plates:view_raw",
  "trajectory:read", "vehicles:search", "watchlist:read", "watchlist:write",
];

const scopeInfo = { scope: "demo", synthetic: true, notice: "Synthetic demo data generated by the demo traffic scenario." };

function alert(over: Record<string, unknown> = {}) {
  return {
    id: 1, code: "ALR-20260930-000001", type: "IMPOSSIBLE_TRAVEL", severity: "HIGH", status: "NEW",
    created_at: "2026-09-30T12:20:49+00:00", updated_at: "2026-09-30T12:20:49+00:00", camera_id: "CAM-06", global_vehicle_id: 34,
    observation_id: 37, title: "Impossible travel: plate UP32HN4412 at CAM-01 and CAM-06",
    reason: "Plate UP32HN4412 was read at CAM-01 and CAM-06 45s apart, but the shortest allowed road path (8.09 km) needs at least 364s.",
    details: { dt_s: 44.6, min_travel_s: 364.1, rule: { type: "IMPOSSIBLE_TRAVEL", severity: "HIGH", min_plate_confidence: 0.75, max_ratio: 0.6, cooldown_s: 600 } },
    confidence: 0.9994, evidence_id: null, occurrences: 1, acknowledged_by: null, acknowledged_at: null, resolved_by: null, resolved_at: null,
    resolution_note: null, is_demo: true, ...over,
  };
}

type Handler = (url: URL, init: RequestInit | undefined) => unknown;
let routes: Record<string, Handler>;
let calls: { method: string; path: string; search: string; body: unknown }[];

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), { status, headers: { "Content-Type": "application/json" } });
}

beforeEach(() => {
  sessionStorage.setItem("nirnay.token", "test-token");
  calls = [];
  live.handlers.clear();
  routes = {
    "GET /api/auth/me": () => ({ id: 1, username: "admin", full_name: null, role: "admin", permissions: ALL_PERMS, can_view_raw_plates: true }),
    "GET /api/cameras": () => ({ ...scopeInfo, cameras: [{ id: "CAM-06", name: "Polytechnic Chauraha", is_demo: true }] }),
    "GET /api/alerts/rules": () => ({ rules: { IMPOSSIBLE_TRAVEL: {}, WRONG_WAY: {}, WATCHLIST_MATCH: { enabled: true, fuzzy_max_distance: 1, cooldown_s: 120 } }, note: "Alerts are only raised by these explicit rules." }),
  };
  vi.stubGlobal("fetch", vi.fn(async (input: RequestInfo | URL, init?: RequestInit) => {
    const url = new URL(String(input), "http://localhost");
    const method = (init?.method ?? "GET").toUpperCase();
    calls.push({ method, path: url.pathname, search: url.search, body: init?.body ? JSON.parse(String(init.body)) : undefined });
    const h = routes[`${method} ${url.pathname}`];
    if (!h) return json({ detail: `no mock for ${method} ${url.pathname}` }, 404);
    const r = h(url, init);
    return r instanceof Response ? r : json(r);
  }));
});

afterEach(() => {
  cleanup();
  vi.unstubAllGlobals();
  sessionStorage.clear();
});

function renderAt(path: string, routeEl: { path: string; el: ReactNode }) {
  const qc = new QueryClient({ defaultOptions: { queries: { retry: false } } });
  return render(
    <QueryClientProvider client={qc}>
      <AuthProvider>
        <ScopeProvider>
          <MemoryRouter initialEntries={[path]}>
            <Routes>
              <Route path={routeEl.path} element={routeEl.el} />
            </Routes>
          </MemoryRouter>
        </ScopeProvider>
      </AuthProvider>
    </QueryClientProvider>,
  );
}

describe("Alerts page", () => {
  it("lists alerts with filters from the URL and acknowledges via POST /api/alerts/{code}/acknowledge", async () => {
    let current = alert();
    routes["GET /api/alerts"] = () => ({ ...scopeInfo, total: 1, counts_7d: { NEW: 1 }, results: [current] });
    routes["POST /api/alerts/ALR-20260930-000001/acknowledge"] = () => {
      current = alert({ status: "ACKNOWLEDGED", acknowledged_by: "admin", acknowledged_at: "2026-09-30T12:40:00+00:00" });
      return current;
    };
    renderAt("/alerts?status=OPEN&severity=HIGH", { path: "/alerts", el: <Alerts /> });

    const row = await screen.findByTestId("alert-row-ALR-20260930-000001");
    expect(within(row).getByText("IMPOSSIBLE_TRAVEL")).toBeInTheDocument();
    expect(screen.getByText("Synthetic demo data generated by the demo traffic scenario.")).toBeInTheDocument();
    const list = calls.find((c) => c.path === "/api/alerts");
    expect(list?.search).toContain("status=OPEN");
    expect(list?.search).toContain("severity=HIGH");

    await userEvent.click(within(row).getByRole("button", { name: "Ack" }));
    await waitFor(() => expect(calls.some((c) => c.method === "POST" && c.path === "/api/alerts/ALR-20260930-000001/acknowledge")).toBe(true));
    await waitFor(() => expect(within(screen.getByTestId("alert-row-ALR-20260930-000001")).getByText("ACKNOWLEDGED")).toBeInTheDocument());
  });

  it("resolves with a note and prepends live alert_created events", async () => {
    let server = [alert()];
    routes["GET /api/alerts"] = () => ({ ...scopeInfo, total: server.length, counts_7d: { NEW: server.length }, results: server });
    routes["POST /api/alerts/ALR-20260930-000001/resolve"] = () => alert({ status: "RESOLVED", resolved_by: "admin", resolution_note: "misread plate" });
    renderAt("/alerts", { path: "/alerts", el: <Alerts /> });
    const first = await screen.findByTestId("alert-row-ALR-20260930-000001");

    await userEvent.click(within(first).getByRole("button", { name: "Resolve…" }));
    const dialog = await screen.findByRole("dialog");
    await userEvent.type(within(dialog).getByRole("textbox"), "misread plate");
    await userEvent.click(within(dialog).getByRole("button", { name: "Resolve" }));
    await waitFor(() => {
      const c = calls.find((x) => x.method === "POST" && x.path.endsWith("/resolve"));
      expect(c?.body).toEqual({ note: "misread plate" });
    });

    const fresh = alert({ id: 7, code: "ALR-20260930-000007", type: "WRONG_WAY", title: "Wrong-way vehicle at CAM-06" });
    server = [fresh, ...server];
    act(() => live.handlers.get("alert_created")?.forEach((h) => h({ type: "alert_created", data: fresh })));
    const row = await screen.findByTestId("alert-row-ALR-20260930-000007");
    expect(row.className).toContain("bg-cyan-500/15"); // brief live highlight
    await waitFor(() => expect(calls.filter((c) => c.path === "/api/alerts").length).toBeGreaterThanOrEqual(2)); // re-synced from server
  });
});

describe("Alert detail", () => {
  it("shows the reason, the rule configuration and the audit history", async () => {
    routes["GET /api/alerts/ALR-20260930-000001"] = () => ({
      ...alert({ status: "ACKNOWLEDGED" }),
      vehicle_code: "VEH-000034",
      evidence: null,
      history: [{ id: 9, ts: "2026-09-30T12:40:00+00:00", user_id: 1, username: "operator", role: "operator", action: "alert.acknowledge", resource_type: "alert", resource_id: "ALR-20260930-000001", details: { from: "NEW", to: "ACKNOWLEDGED", note: "checking footage" }, ip: null, success: true }],
    });
    renderAt("/alerts/ALR-20260930-000001", { path: "/alerts/:ref", el: <AlertDetail /> });
    expect(await screen.findByText(/shortest allowed road path/)).toBeInTheDocument();
    expect(screen.getByText("min_plate_confidence")).toBeInTheDocument();
    expect(screen.getByText("checking footage")).toBeInTheDocument();
    expect(screen.getByRole("link", { name: "VEH-000034" })).toHaveAttribute("href", "/vehicles/VEH-000034");
    expect(screen.getByRole("button", { name: "Resolve" })).toBeInTheDocument();
    expect(screen.queryByRole("button", { name: "Acknowledge" })).toBeNull();
  });
});

describe("Analytics page", () => {
  it('shows "No data available for this period." for an empty summary', async () => {
    routes["GET /api/analytics/summary"] = () => ({
      ...scopeInfo, since: "2026-09-30T13:00:00+00:00", until: "2026-09-30T14:00:00+00:00", has_data: false,
      message: "No data available for this period.", totals: null, observations: 0, plate_read_rate: null, by_class: {}, by_camera: {},
    });
    renderAt("/analytics?period=15m", { path: "/analytics", el: <Analytics /> });
    expect(await screen.findByText("No data available for this period.")).toBeInTheDocument();
    expect(calls.find((c) => c.path === "/api/analytics/summary")?.search).toContain("period=15m");
  });

  it("renders the OD heatmap and drills into a cell (audited endpoint) for authorised users", async () => {
    routes["GET /api/analytics/od-matrix"] = () => ({
      ...scopeInfo, since: "2026-09-30T11:30:00+00:00", until: "2026-09-30T12:30:00+00:00", has_data: true, message: null,
      cells: [{ origin: "CAM-01", destination: "CAM-03", count: 9, median_travel_s: 342.9 }], suppressed_journeys: 0, min_count: 1,
      cameras: ["CAM-01", "CAM-03"], total_journeys: 9, camera_names: { "CAM-01": "Charbagh", "CAM-03": "Hazratganj" }, drilldown_allowed: true,
    });
    routes["GET /api/analytics/od-matrix/vehicles"] = () => ({
      ...scopeInfo, has_data: true, message: null, origin: "CAM-01", destination: "CAM-03",
      journeys: [{ global_vehicle_id: 16, journey_index: 0, start: "2026-09-30T12:19:09+00:00", end: "2026-09-30T12:27:07+00:00", cameras: ["CAM-01", "CAM-02", "CAM-03"], vehicle_code: "VEH-000016", plate_text: "PSN-1A2B3C4D5E" }],
    });
    renderAt("/analytics?tab=od", { path: "/analytics", el: <Analytics /> });
    await userEvent.click(await screen.findByRole("button", { name: "Journeys CAM-01 to CAM-03" }));
    expect(await screen.findByText("PSN-1A2B3C4D5E")).toBeInTheDocument();
    const drill = calls.find((c) => c.path === "/api/analytics/od-matrix/vehicles");
    expect(drill?.search).toContain("origin=CAM-01");
    expect(drill?.search).toContain("destination=CAM-03");
  });
});

describe("Watchlist page", () => {
  it("explains rule-only alerting and creates an entry with the backend fields", async () => {
    let entries: unknown[] = [];
    routes["GET /api/watchlist"] = () => ({ results: entries });
    routes["POST /api/watchlist"] = (_u, init) => {
      const b = JSON.parse(String(init?.body));
      const e = { id: 1, ...b, active: true, created_by: "admin", created_at: "2026-09-30T12:40:00+00:00", last_match_at: null, match_count: 0 };
      entries = [e];
      return json(e, 201);
    };
    renderAt("/watchlist", { path: "/watchlist", el: <Watchlist /> });
    expect(await screen.findByText(/No plate is ever flagged by default/)).toBeInTheDocument();
    expect(await screen.findByText(/The watchlist is empty/)).toBeInTheDocument();

    await userEvent.click(screen.getByRole("button", { name: "+ Add plate" }));
    const dialog = await screen.findByRole("dialog");
    const [plate, reason] = within(dialog).getAllByRole("textbox");
    await userEvent.type(plate, "UP32HN4412");
    await userEvent.type(reason, "stolen vehicle report");
    await userEvent.click(within(dialog).getByRole("button", { name: "Add to watchlist" }));
    await waitFor(() => {
      const c = calls.find((x) => x.method === "POST" && x.path === "/api/watchlist");
      expect(c?.body).toMatchObject({ plate: "UP32HN4412", reason: "stolen vehicle report", priority: "MEDIUM", match_mode: "exact", expires_at: null });
    });
    expect(await screen.findByText("UP32HN4412")).toBeInTheDocument();
  });
});
